# .github/workflows/ci.yml

name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            git \
            curl \
            ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir \
            torch \
            torchaudio \
            --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir \
            git+https://github.com/openai/whisper.git

      - name: Install project dependencies
        run: |
          if [ -f egs/whisper/requirements.txt ]; then
            pip install -r egs/whisper/requirements.txt
          fi

      - name: Run tests
        run: |
          echo "Add your test commands here"
          # python -m pytest tests/ || true

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t mago-op-whisper:latest .

      - name: Test Docker image
        run: |
          docker run --rm mago-op-whisper:latest python --version
          docker run --rm mago-op-whisper:latest pip list | grep -E "(torch|whisper)"
